server:
  port: 5006
  servlet:
    context-path: /student-affair-server
  tomcat:
    threads:
      # 将最大线程数从默认的200调高。我们可以先尝试一个更高的值，例如800
      max: 800
    # 同样调高连接等待队列的长度，以应对瞬时高峰
    accept-count: 1000

spring:
  datasource:
    url: jdbc:dm://172.20.193.204:5236/EDU_DATABASE?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    driver-class-name: dm.jdbc.driver.DmDriver
    username: SYSDBA
    password: SYSDBA001
  application:
    name: student-affair-server
  cloud:
    nacos:
      server-addr: 172.20.193.204:8848
      discovery:
        username: nacos
        password: Zeh19990808*

  data:
    redis:
      cluster:
        nodes:
          - 172.20.193.204:7001
          - 172.20.193.204:7002
          - 172.20.193.204:7003
          - 172.20.193.204:7004
          - 172.20.193.204:7005
          - 172.20.193.204:7006
      password: 1q2w3e4r
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 200
          max-idle: 50
          min-idle: 10
          max-wait: -1ms
        cluster:
          refresh:
            adaptive: true


springdoc:
  swagger-ui:
    doc-expansion: none

management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    edu.qhjy: debug